name: Integration request
description: File an integration request
title: "[Integrations] <title>"
labels: [integration]
body:
- type: checkboxes
  attributes:
    label: Is this for an existing app(s)?
    options:
    - label: "Yes"
    - label: "No"
      required: false
- type: textarea
  attributes:
    label: Business need
    description: A concise description of the business need.
  validations:
    required: false
- type: textarea
  attributes:
    label: Integration description
    description: A concise description of what tools need to be integrated/workflow that needs to be set up
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps in workflow/integration
    description: Please list detailed steps in the workflow and expected behavior
    placeholder: |
      1. 
      2.
      3. 
      4. 
  validations:
    required: false
- type: textarea
  attributes:
    label: Tools/applications involved
    description: Please list all relevant tools and applications needed
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context. 

      Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
